version: '3.8'
services:
  lodgement-tool:
    image: mycrmfinance/mycrm-testable-lodgement:latest
    ports:
      - "8080:8080"
    environment:
      - LodgementSettings__SubmissionUrl=https://host.docker.internal:7182/submit
      - LodgementSettings__ValidationUrl=https://host.docker.internal:7182/validate
      - LodgementSettings__Country=Australia
      - LodgementSettings__Version=2.6.35
      - LodgementSettings__IgnoreSSL=true
      - LodgementSettings__MediaType=application/json